import { useState, useEffect } from "react";

// API Configuration
const API_BASE_URL = "http://localhost:8080/api";

// Interface to define the shape of user data
interface UserData {
  user_id: number;
  name: string;
  email: string;
  badge_number: string;
  role: "Admin" | "Manager" | "picker";
  created_at: string;
  updated_at: string;
  last_login: string | null;
}

// Interface for the Create User form (ID and dates are generated by backend)
type CreateUserForm = {
  name: string;
  email: string;
  badge_number: string;
  role: "Admin" | "Manager" | "picker";
};

const ViewUsers = () => {
  // State management
  const [users, setUsers] = useState<UserData[]>([]);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(true);

  // Edit State
  const [editingUser, setEditingUser] = useState<UserData | null>(null);

  // Create User State
  const [isCreateOpen, setIsCreateOpen] = useState<boolean>(false);
  const [createError, setCreateError] = useState<string>("");
  const [newUser, setNewUser] = useState<CreateUserForm>({
    name: "",
    email: "",
    badge_number: "",
    role: "picker",
  });

  // Fetch users on component mount
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        // API Call - Get all users
        const res = await fetch(`${API_BASE_URL}/v1/users`);
        if (!res.ok) throw new Error("Failed to fetch");
        
        const data = await res.json();
        
        // Ensure data is an array before setting state
        setUsers(Array.isArray(data) ? data : []);
      } catch (error) {
        console.error("Error fetching users:", error);
        setUsers([]); 
      } finally {
        setIsLoading(false);
      }
    };

    fetchUsers();
  }, []);

  // --- CREATE USER HANDLERS ---

  // 1. Handle Input Changes for New User
  const handleCreateChange = (field: keyof CreateUserForm, value: string) => {
    setNewUser(prev => ({ ...prev, [field]: value }));
  };

  // 2. Submit New User to API
  const handleCreateUser = async () => {
    // Basic validation
    if (!newUser.name || !newUser.email || !newUser.badge_number) {
      setCreateError("Name, Email, and Badge Number are required.");
      return;
    }

    try {
      // API Call - Create User (POST)
      // Password will be hashed by the backend
      const res = await fetch(`${API_BASE_URL}/v1/users/create`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...newUser,
          password: "temp_default_password" 
        }),
      });

      if (!res.ok) {
        const errorData = await res.json();
        console.error("API Error Response:", errorData);
        if (errorData.detail) {
          if (Array.isArray(errorData.detail)) {
            // Validation errors are often an array
            const errorMessages = errorData.detail.map((err: any) => 
              `${err.loc?.join(' -> ')}: ${err.msg}`
            ).join(', ');
            throw new Error(errorMessages);
          } else {
            throw new Error(errorData.detail);
          }
        }
        throw new Error("Failed to create user");
      }

      const createdUser = await res.json(); 
      
      // Update UI: Add new user to the list immediately
      setUsers(prev => [...prev, createdUser]);
      
      // Reset Form and Close Modal
      setNewUser({ name: "", email: "", badge_number: "", role: "picker" });
      setIsCreateOpen(false);
      setCreateError("");
      alert("User created successfully!");

    } catch (error) {
      console.error(error);
      setCreateError("Failed to create user. Check backend logs.");
    }
  };

  // --- EDIT & DELETE HANDLERS --- 

  // Delete User Handler
  const handleDelete = async (user_id: number) => {
    const confirmDelete = window.confirm("Are you sure you want to remove this user?");
    if (!confirmDelete) return;

    try {
      // API Call - Delete User
      const res = await fetch(`${API_BASE_URL}/v1/users/${user_id}`, { method: 'DELETE' });
      
      if (!res.ok) throw new Error("Failed to delete");

      // Update UI: Remove the user with this ID from the state
      setUsers((prev) => prev.filter((user) => user.user_id !== user_id));
      
    } catch (error) {
      console.error(error);
      alert("Failed to delete user");
    }
  };

  // 1. Open the edit modal with the user's data
  const handleEditClick = (user: UserData) => {
    setEditingUser({ ...user }); 
  };

  // 2. Handle input changes inside the edit modal
  const handleEditChange = (field: keyof UserData, value: string) => {
    if (editingUser) {
      setEditingUser({ ...editingUser, [field]: value } as UserData);
    }
  };

  // 3. Save changes (PUT Request)
  const handleSaveUser = async () => {
    if (!editingUser) return;

    try {
      // API Call - Update User
      const res = await fetch(`${API_BASE_URL}/v1/users/${editingUser.user_id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(editingUser),
      });

      if (!res.ok) throw new Error("Failed to update");
      
      const updatedUser = await res.json(); 
      
      // Update local state: Find the user by ID and replace with new data
      setUsers(prev => prev.map(u => (u.user_id === editingUser.user_id ? updatedUser : u)));
      
      setEditingUser(null); // Close modal
      alert("User updated successfully!");
    } catch (error) {
      console.error(error);
      alert("Failed to update user");
    }
  };

  // Search filter logic
  const filteredUsers = users.filter(user => 
    user.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
    user.role.toLowerCase().includes(searchTerm.toLowerCase()) ||
    user.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="max-w-6xl mx-auto bg-white p-8 rounded-xl shadow-lg border border-slate-200 my-10">
      
      {/* Header Section */}
      <div className="flex flex-col md:flex-row justify-between items-end mb-6 gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">User Management</h2>
          <p className="text-slate-500 text-sm">View and manage system access.</p>
        </div>
        
        <div className="flex gap-3 w-full md:w-auto">
          {/* Search Bar */}
          <div className="relative w-full">
            <input 
              type="text" 
              placeholder="Search users..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-4 pr-10 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none w-full"
            />
          </div>

          {/* NEW: Create User Button */}
          <button 
            onClick={() => setIsCreateOpen(true)}
            className="bg-blue-600 hover:bg-blue-700 text-white font-medium px-4 py-2 rounded-lg transition-colors whitespace-nowrap flex items-center gap-2"
          >
            <span>+</span> Add User
          </button>
        </div>
      </div>

      {/* Loading State */}
      {isLoading ? (
        <div className="text-center py-20 text-slate-400 animate-pulse">
          Loading users...
        </div>
      ) : (
        /* Table */
        <div className="overflow-x-auto rounded-lg border border-slate-200">
          <table className="w-full text-left border-collapse min-w-[900px]">
            <thead>
              <tr className="bg-slate-50 text-slate-600 text-xs uppercase tracking-wider">
                <th className="p-4 font-semibold border-b">User</th>
                <th className="p-4 font-semibold border-b">Badge</th>
                <th className="p-4 font-semibold border-b">Role</th>
                <th className="p-4 font-semibold border-b">Last Login</th>
                <th className="p-4 font-semibold border-b text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredUsers.length > 0 ? (
                filteredUsers.map((user) => (
                  <tr key={user.user_id} className="hover:bg-slate-50 transition-colors">
                    
                    {/* 1. User Info (Avatar + Name + Email) */}
                    <td className="p-4">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold text-sm uppercase">
                          {user.email.substring(0, 2)}
                        </div>
                        <div>
                          <div className="font-medium text-slate-900">{user.name}</div>
                          <div className="text-sm text-slate-500">{user.email}</div>
                        </div>
                      </div>
                    </td>

                    {/* 2. Badge Number */}
                    <td className="p-4 text-sm text-slate-600 font-mono">{user.badge_number}</td>

                    {/* 3. Role Badge */}
                    <td className="p-4">
                      <span
                        className={`px-2 py-1 rounded-full text-xs font-bold border capitalize ${
                          user.role === "Admin"
                            ? "bg-purple-100 text-purple-700 border-purple-200"
                            : user.role === "Manager"
                            ? "bg-blue-100 text-blue-700 border-blue-200"
                            : "bg-slate-100 text-slate-600 border-slate-200"
                        }`}
                      >
                        {user.role}
                      </span>
                    </td>

                    {/* 4. Last Login */}
                    <td className="p-4 text-sm text-slate-500 font-mono">
                      {user.last_login || "Never"}
                    </td>

                    {/* 5. Actions (Edit / Delete) */}
                    <td className="p-4 text-right space-x-2">
                      <button 
                        onClick={() => handleEditClick(user)}
                        className="text-slate-400 hover:text-blue-600 font-medium text-sm px-3 py-1 rounded hover:bg-blue-50 transition-all"
                      >
                        Edit
                      </button>
                      <button 
                        onClick={() => handleDelete(user.user_id)}
                        className="text-slate-400 hover:text-red-600 font-medium text-sm px-3 py-1 rounded hover:bg-red-50 transition-all"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="p-8 text-center text-slate-400 italic">
                    No users found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      {/* --- CREATE MODAL (Popup) --- */}
      {isCreateOpen && (
        <div className="fixed inset-0 bg-black/50 flex justify-center items-center z-50">
          <div className="bg-white p-6 rounded-lg shadow-xl w-96 animate-in fade-in zoom-in duration-200">
            <h3 className="text-xl font-bold text-slate-800 mb-4">Create New User</h3>
            
            {/* Error Message */}
            {createError && (
              <div className="bg-red-50 text-red-600 p-2 text-sm rounded mb-4 border border-red-200">
                {createError}
              </div>
            )}

            <div className="space-y-4">
              {/* Name Input */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Name</label>
                <input
                  value={newUser.name}
                  onChange={(e) => handleCreateChange("name", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                  placeholder="John Doe"
                />
              </div>

              {/* Email Input */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
                <input
                  type="email"
                  value={newUser.email}
                  onChange={(e) => handleCreateChange("email", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                  placeholder="john@example.com"
                />
              </div>

              {/* Badge Input */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Badge Number</label>
                <input
                  value={newUser.badge_number}
                  onChange={(e) => handleCreateChange("badge_number", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                  placeholder="e.g. 12345"
                />
              </div>

              {/* Role Select */}
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Role</label>
                <select
                  value={newUser.role}
                  onChange={(e) => handleCreateChange('role', e.target.value as CreateUserForm['role'])}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none bg-white"
                >
                  <option value="picker">picker</option>
                  <option value="Manager">Manager</option>
                  <option value="Admin">Admin</option>
                </select>
              </div>
            </div>

            {/* Modal Actions */}
            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => {
                   setIsCreateOpen(false);
                   setCreateError("");
                }}
                className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg"
              >
                Cancel
              </button>
              <button
                onClick={handleCreateUser}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Create User
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- EDIT MODAL (Popup) --- */}
      {editingUser && (
        <div className="fixed inset-0 bg-black/50 flex justify-center items-center z-50">
          <div className="bg-white p-6 rounded-lg shadow-xl w-96 animate-in fade-in zoom-in duration-200">
            <h3 className="text-xl font-bold text-slate-800 mb-4">Edit User</h3>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Name</label>
                <input
                  value={editingUser.name}
                  onChange={(e) => handleEditChange("name", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Email</label>
                <input
                  type="email"
                  value={editingUser.email}
                  onChange={(e) => handleEditChange("email", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Badge Number</label>
                <input
                  value={editingUser.badge_number}
                  onChange={(e) => handleEditChange("badge_number", e.target.value)}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Role</label>
                <select
                  value={editingUser.role}
                  onChange={(e) => handleEditChange('role', e.target.value as UserData['role'])}
                  className="w-full p-2 border rounded-md focus:ring-2 focus:ring-blue-500 outline-none bg-white"
                >
                  <option value="picker">picker</option>
                  <option value="Manager">Manager</option>
                  <option value="Admin">Admin</option>
                </select>
              </div>
            </div>

            <div className="flex justify-end gap-3 mt-6">
              <button
                onClick={() => setEditingUser(null)}
                className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg"
              >
                Cancel
              </button>
              <button
                onClick={handleSaveUser}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
              >
                Save Changes
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="mt-4 text-xs text-slate-400 text-right">Total Users: {filteredUsers.length}</div>
    </div>
  );
};

export default ViewUsers;
