import { useState, useEffect, useMemo } from "react";
import {Search, UserPlus, Trash2, X, Pencil, CheckCircle2, AlertTriangle,} from "lucide-react";
import { API_BASE_URL } from "../config/api";

/**
 * User data as stored in backend.
 * Includes timestamps for creation, updates, and last login.
 */
interface UserData {
  user_id: number;
  name: string;
  email: string;
  badge_number: string;
  role: "admin" | "manager" | "picker";
  created_at: string;
  updated_at: string;
  last_login: string | null;
}

// Interface for the Create User form (ID and dates are generated by backend)
type CreateUserForm = {
  name: string;
  email: string;
  badge_number: string;
  role: "admin" | "manager" | "picker";
  password: string;
};

const ViewUsers = () => {
  // Main data state
  const [users, setUsers] = useState<UserData[]>([]);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [isLoading, setIsLoading] = useState<boolean>(true);

  // Edit/save state
  const [editingUser, setEditingUser] = useState<UserData | null>(null);
  const [isSaving, setIsSaving] = useState<boolean>(false);
  const [editPassword, setEditPassword] = useState<string>("");
  const [pendingRoleChange, setPendingRoleChange] = useState<string | null>(null);

  // Create new user modal state
  const [isCreateOpen, setIsCreateOpen] = useState<boolean>(false);
  const [createError, setCreateError] = useState<string>("");
  const [newUser, setNewUser] = useState<CreateUserForm>({
    name: "",
    email: "",
    badge_number: "",
    role: "picker",
    password: "",
  });

  // Delete confirmation modal state
  const [deleteTarget, setDeleteTarget] = useState<UserData | null>(null);
  const [isDeleting, setIsDeleting] = useState<boolean>(false);

  // Toast notification state for feedback
  const [toast, setToast] = useState<{
    type: "success" | "error";
    message: string;
  } | null>(null);

  const showToast = (t: { type: "success" | "error"; message: string }) => {
    setToast(t);
    window.setTimeout(() => setToast(null), 2500);
  };

  // Fetch all users on component mount.
  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const res = await fetch(`${API_BASE_URL}/v1/users`);
        if (!res.ok) throw new Error("Failed to fetch");

        const data = await res.json();
        setUsers(Array.isArray(data) ? data : []);
      } catch (error) {
        console.error("Error fetching users:", error);
        setUsers([]);
        showToast({ type: "error", message: "Failed to fetch users." });
      } finally {
        setIsLoading(false);
      }
    };

    fetchUsers();
  }, []);

  // --- CREATE USER HANDLERS ---

  const handleCreateChange = (field: keyof CreateUserForm, value: string) => {
    setNewUser((prev) => ({ ...prev, [field]: value }));
  };

  const handleCreateUser = async () => {
    // Basic validation
    if (!newUser.name || !newUser.email || !newUser.badge_number) {
      setCreateError("Name, Email, and Badge Number are required.");
      return;
    }

    // Password required for Admin and Manager roles
    const requiresPassword = newUser.role === "admin" || newUser.role === "manager";
    if (requiresPassword && !newUser.password) {
      setCreateError("Password is required for Admin and Manager roles.");
      return;
    }

    try {
      // API Call - Create User (POST)
      const requestBody = {
        name: newUser.name,
        email: newUser.email,
        badge_number: newUser.badge_number,
        role: newUser.role,
        password: newUser.password || newUser.badge_number // Use badge_number as password for pickers
      }
      console.log("Creating user with data:", requestBody);
      
      const res = await fetch(`${API_BASE_URL}/v1/users/create`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          ...newUser,
          password: "temp_default_password" // TODO: Implement secure password generation
        }),
      });

      if (!res.ok) {
        const errorData = await res.json();
        console.error("API Error Response:", errorData);
        if (errorData.detail) {
          if (Array.isArray(errorData.detail)) {
            // Validation errors are often an array
            const errorMessages = errorData.detail.map((err: any) => 
              `${err.loc?.join(' -> ')}: ${err.msg}`
            ).join(', ');
            throw new Error(errorMessages);
          } else {
            throw new Error(errorData.detail);
          }
        }
        throw new Error("Failed to create user");
      }

      const createdUser = await res.json(); 
      
      // Update UI: Add new user to the list immediately
      setUsers(prev => [...prev, createdUser]);
      
      // Reset Form and Close Modal
      setNewUser({ name: "", email: "", badge_number: "", role: "picker", password: "" });
      setIsCreateOpen(false);
      setCreateError("");
      showToast({ type: "success", message: "User created successfully!" });
    } catch (error) {
      console.error(error);
      setCreateError("Failed to create user. Check backend logs.");
      showToast({ type: "error", message: "Failed to create user." });
    }
  };

  // --- EDIT & DELETE HANDLERS --- 

  // Delete User Handler
  const handleDelete = async (user_id: number) => {
    const confirmDelete = window.confirm("Are you sure you want to remove this user?");
    if (!confirmDelete) return;

    try {
      // API Call - Delete User
      const res = await fetch(`${API_BASE_URL}/v1/users/${user_id}`, { method: 'DELETE' });
      
      if (!res.ok) throw new Error("Failed to delete");

      // Update UI: Remove the user with this ID from the state
      setUsers((prev) => prev.filter((user) => user.user_id !== user_id));
      
    } catch (error) {
      console.error(error);
      alert("Failed to delete user");
    }
  };

  const handleEditClick = (user: UserData) => {
    setEditingUser({ ...user });
    setEditPassword(""); // Reset password field when opening edit modal
  };

  const handleEditChange = (field: keyof UserData, value: string) => {
    if (!editingUser) return;
    setEditingUser({ ...editingUser, [field]: value } as UserData);
  };

  const handleSaveUser = async () => {
    if (!editingUser) return;

    setIsSaving(true);
    try {
      // Build the update payload
      const updatePayload: Record<string, unknown> = { ...editingUser };
      
      // Include password if provided (for Admin/Manager) or use badge_number for picker
      if (editingUser.role === "picker") {
        updatePayload.password = editingUser.badge_number;
      } else if (editPassword) {
        updatePayload.password = editPassword;
      }

      const res = await fetch(`${API_BASE_URL}/v1/users/${editingUser.user_id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(updatePayload),
      });

      if (!res.ok) throw new Error("Failed to update");

      const updatedUser = await res.json();

      setUsers((prev) =>
        prev.map((u) => (u.user_id === editingUser.user_id ? updatedUser : u))
      );

      setEditingUser(null);
      setEditPassword("");
      showToast({ type: "success", message: "User updated successfully!" });
    } catch (error) {
      console.error(error);
      showToast({ type: "error", message: "Failed to update user." });
    } finally {
      setIsSaving(false);
    }
  };

  // Handle role change with confirmation for switching to picker
  const handleEditRoleChange = (newRole: string) => {
    if (!editingUser) return;
    
    // If switching TO picker from admin/manager, show confirmation
    if (newRole === "picker" && (editingUser.role === "admin" || editingUser.role === "manager")) {
      setPendingRoleChange(newRole);
    } else {
      setEditingUser({ ...editingUser, role: newRole as UserData["role"] });
      // Clear password if switching to picker
      if (newRole === "picker") {
        setEditPassword("");
      }
    }
  };

  const confirmRoleChange = () => {
    if (!editingUser || !pendingRoleChange) return;
    setEditingUser({ ...editingUser, role: pendingRoleChange as UserData["role"] });
    setEditPassword(""); // Clear password when switching to picker
    setPendingRoleChange(null);
  };

  // --- DELETE HANDLERS ---

  const confirmDelete = async () => {
    if (!deleteTarget) return;

    setIsDeleting(true);
    try {
      const res = await fetch(`${API_BASE_URL}/v1/users/${deleteTarget.user_id}`, {
        method: "DELETE",
      });

      if (!res.ok) throw new Error("Failed to delete");

      setUsers((prev) => prev.filter((u) => u.user_id !== deleteTarget.user_id));
      showToast({
        type: "success",
        message: `User "${deleteTarget.name}" deleted.`,
      });
      setDeleteTarget(null);
    } catch (error) {
      console.error(error);
      showToast({ type: "error", message: "Failed to delete user." });
    } finally {
      setIsDeleting(false);
    }
  };

  // Search filter logic
  const filteredUsers = useMemo(() => {
    const q = searchTerm.trim().toLowerCase();
    if (!q) return users;

    return users.filter(
      (user) =>
        user.email.toLowerCase().includes(q) ||
        user.role.toLowerCase().includes(q) ||
        user.name.toLowerCase().includes(q)
    );
  }, [users, searchTerm]);

  return (
    <div className="space-y-6">
      {/* PAGE HEADER*/}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h1 className="text-4xl font-bold text-slate-900">User Management</h1>
          <p className="mt-2 text-slate-500">View and manage system access.</p>
        </div>

        <button
          onClick={() => setIsCreateOpen(true)}
          className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-white font-medium hover:bg-blue-700"
        >
          <UserPlus className="h-5 w-5" />
          Add User
        </button>
      </div>

      {/* Toast / feedback banner */}
      {toast && (
        <div
          className={`rounded-2xl border px-4 py-3 text-sm flex items-start gap-2 ${
            toast.type === "success"
              ? "border-emerald-200 bg-emerald-50 text-emerald-800"
              : "border-red-200 bg-red-50 text-red-800"
          }`}
        >
          {toast.type === "success" ? (
            <CheckCircle2 className="h-5 w-5 mt-0.5" />
          ) : (
            <AlertTriangle className="h-5 w-5 mt-0.5" />
          )}
          <div className="flex-1">{toast.message}</div>
          <button
            className="rounded-lg px-2 py-1 hover:bg-black/5"
            onClick={() => setToast(null)}
            title="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}

      {/* TABLE CARD */}
      <div className="rounded-2xl bg-white border border-slate-200 shadow-sm">
        {/* SEARCH */}
        <div className="p-6 border-b border-slate-100">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-400" />
            <input
              type="text"
              placeholder="Search users..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full rounded-xl border border-slate-200 bg-white pl-12 pr-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>
        </div>

        {/* TABLE */}
        <div className="overflow-x-auto">
          <table className="w-full min-w-[980px] table-fixed">
            <thead>
              <tr className="text-left text-slate-500 text-sm border-b border-slate-100">
                <th className="px-6 py-4 font-semibold">User</th>
                <th className="px-6 py-4 font-semibold w-36">Badge</th>
                <th className="px-6 py-4 font-semibold w-32">Role</th>
                <th className="px-6 py-4 font-semibold w-48">Last Login</th>
                <th className="px-6 py-4 font-semibold text-right w-28">
                  Actions
                </th>
              </tr>
            </thead>

            <tbody className="divide-y divide-slate-100">
              {isLoading ? (
                <tr>
                  <td colSpan={5} className="px-6 py-16 text-center text-slate-400">
                    Loading users…
                  </td>
                </tr>
              ) : filteredUsers.length > 0 ? (
                filteredUsers.map((user) => (
                  <tr key={user.user_id} className="hover:bg-slate-50">
                    {/* User */}
                    <td className="px-6 py-5">
                      <div className="flex items-center gap-3">
                        <div className="h-10 w-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-600 font-bold text-sm uppercase">
                          {(user.name || user.email).substring(0, 2)}
                        </div>
                        <div>
                          <div className="font-semibold text-slate-900">
                            {user.name}
                          </div>
                          <div className="text-sm text-slate-500">
                            {user.email}
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* Badge */}
                    <td className="px-6 py-5 text-sm text-slate-700 font-mono">
                      {user.badge_number || "—"}
                    </td>

                    {/* Role */}
                    <td className="px-6 py-5">
                      <span
                        className={`px-2.5 py-1 rounded-full text-xs font-medium border ${
                          user.role === "admin"
                            ? "bg-purple-100 text-purple-700 border-purple-200"
                            : user.role === "manager"
                            ? "bg-blue-100 text-blue-700 border-blue-200"
                            : "bg-slate-100 text-slate-600 border-slate-200"
                        }`}
                      >
                        {user.role}
                      </span>
                    </td>

                    {/* Last Login */}
                    <td className="px-6 py-5 text-sm text-slate-500 font-mono">
                      {user.last_login || "Never"}
                    </td>

                    {/* Actions */}
                    <td className="px-6 py-5">
                      <div className="flex items-center justify-end gap-2">
                        <button
                          onClick={() => handleEditClick(user)}
                          className="inline-flex h-10 w-10 items-center justify-center rounded-xl text-slate-600 hover:bg-slate-50 hover:text-green-600"
                          title="Edit user"
                        >
                          <Pencil className="h-5 w-5" />
                        </button>

                        <button
                          onClick={() => setDeleteTarget(user)}
                          className="inline-flex h-10 w-10 items-center justify-center rounded-xl text-slate-600 hover:bg-slate-50 hover:text-red-600"
                          title="Delete user"
                        >
                          <Trash2 className="h-5 w-5" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={5} className="px-6 py-16 text-center text-slate-400">
                    No users match “{searchTerm}”.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* FOOTER */}
        <div className="px-6 py-4 border-t border-slate-100 text-sm text-slate-500 flex items-center justify-between">
          <span>
            Showing <span className="font-medium">{filteredUsers.length}</span>{" "}
            result{filteredUsers.length === 1 ? "" : "s"}
          </span>
          <span className="hidden sm:block">Total users: {users.length}</span>
        </div>
      </div>

      {/* --- CREATE MODAL --- */}
      {isCreateOpen && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) {
              setIsCreateOpen(false);
              setCreateError("");
            }
          }}
        >
          <div className="w-full max-w-md rounded-2xl bg-white shadow-xl border border-slate-200 overflow-hidden max-h-[90vh] flex flex-col">
            {/* Header */}
            <div className="px-6 py-5 border-b border-slate-100 flex items-start justify-between gap-4 sticky top-0 bg-white z-10">
              <div>
                <div className="text-lg font-semibold text-slate-900">
                  Create New User
                </div>
                <div className="mt-1 text-sm text-slate-500">Add a new user</div>
              </div>

              <button
                type="button"
                onClick={() => {
                  setIsCreateOpen(false);
                  setCreateError("");
                }}
                className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100"
                title="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="p-6 space-y-4 overflow-y-auto flex-1">
              {createError && (
                <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
                  {createError}
                </div>
              )}

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">
                  Name
                </label>
                <input
                  value={newUser.name}
                  onChange={(e) => handleCreateChange("name", e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="John Doe"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">
                  Email
                </label>
                <input
                  type="email"
                  value={newUser.email}
                  onChange={(e) => handleCreateChange("email", e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="john@example.com"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">
                  Role
                </label>
                <select
                  value={newUser.role}
                  onChange={(e) => {
                    handleCreateChange("role", e.target.value as CreateUserForm["role"]);
                    // Clear password when switching to picker
                    if (e.target.value === "picker") {
                      handleCreateChange("password", "");
                    }
                  }}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="picker">Picker</option>
                  <option value="manager">Manager</option>
                  <option value="admin">Admin</option>
                </select>
                <p className="mt-1 text-xs text-slate-500">
                  {newUser.role === "picker" 
                    ? "Pickers log in using their badge number only."
                    : "Admins and Managers require a password to log in."}
                </p>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">
                  Badge Number
                </label>
                <input
                  value={newUser.badge_number}
                  onChange={(e) =>
                    handleCreateChange("badge_number", e.target.value)
                  }
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                  placeholder="e.g. 12345"
                />
              </div>

              {/* Password field - only shown for Admin and Manager */}
              {(newUser.role === "admin" || newUser.role === "manager") && (
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">
                    Password
                  </label>
                  <input
                    type="password"
                    value={newUser.password}
                    onChange={(e) => handleCreateChange("password", e.target.value)}
                    className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter a secure password"
                  />
                  <p className="mt-1 text-xs text-slate-500">
                    This password will be used to log in to the web dashboard.
                  </p>
                </div>
              )}
            </div>

            {/* Actions */}
            <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3 sticky bottom-0 bg-white">
              <button
                onClick={() => {
                  setIsCreateOpen(false);
                  setCreateError("");
                }}
                className="rounded-xl px-4 py-2 border border-slate-200 text-slate-700 hover:bg-slate-50"
              >
                Cancel
              </button>
              <button
                onClick={handleCreateUser}
                className="rounded-xl bg-blue-600 px-4 py-2 text-white font-medium hover:bg-blue-700"
              >
                Create User
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- EDIT MODAL  --- */}
      {editingUser && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setEditingUser(null);
          }}
        >
          <div className="w-full max-w-md rounded-2xl bg-white shadow-xl border border-slate-200 overflow-hidden max-h-[90vh] flex flex-col">
            {/* Header */}
            <div className="px-6 py-5 border-b border-slate-100 flex items-start justify-between gap-4 sticky top-0 bg-white z-10">
              <div>
                <div className="text-lg font-semibold text-slate-900">Edit User</div>
                <div className="mt-1 text-sm text-slate-500">Update user details</div>
              </div>

              <button
                type="button"
                onClick={() => setEditingUser(null)}
                className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100"
                title="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="p-6 space-y-4 overflow-y-auto flex-1">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Name</label>
                <input
                  value={editingUser.name}
                  onChange={(e) => handleEditChange("name", e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Email</label>
                <input
                  type="email"
                  value={editingUser.email}
                  onChange={(e) => handleEditChange("email", e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Role</label>
                <select
                  value={editingUser.role}
                  onChange={(e) => handleEditRoleChange(e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                >
                  <option value="picker">Picker</option>
                  <option value="manager">Manager</option>
                  <option value="admin">Admin</option>
                </select>
                <p className="mt-1 text-xs text-slate-500">
                  {editingUser.role === "picker"
                    ? "Pickers log in using their badge number only."
                    : "Admins and Managers require a password to log in."}
                </p>
              </div>

              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-1">Badge Number</label>
                <input
                  value={editingUser.badge_number}
                  onChange={(e) => handleEditChange("badge_number", e.target.value)}
                  className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>

              {/* Password field - only shown for Admin and Manager */}
              {(editingUser.role === "admin" || editingUser.role === "manager") && (
                <div>
                  <label className="block text-sm font-semibold text-slate-700 mb-1">
                    New Password
                  </label>
                  <input
                    type="password"
                    value={editPassword}
                    onChange={(e) => setEditPassword(e.target.value)}
                    className="w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Leave blank to keep current password"
                  />
                  <p className="mt-1 text-xs text-slate-500">
                    Only fill this if you want to change the password.
                  </p>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3 sticky bottom-0 bg-white">
              <button
                onClick={() => {
                  setEditingUser(null);
                  setEditPassword("");
                }}
                className="rounded-xl px-4 py-2 border border-slate-200 text-slate-700 hover:bg-slate-50"
                disabled={isSaving}
              >
                Cancel
              </button>
              <button
                onClick={handleSaveUser}
                disabled={isSaving}
                className="rounded-xl bg-blue-600 px-4 py-2 text-white font-medium hover:bg-blue-700 disabled:opacity-60"
              >
                {isSaving ? "Saving..." : "Save Changes"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- ROLE CHANGE CONFIRMATION MODAL --- */}
      {pendingRoleChange && (
        <div
          className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 px-4"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setPendingRoleChange(null);
          }}
        >
          <div className="w-full max-w-md rounded-2xl bg-white shadow-xl border border-slate-200 overflow-hidden">
            {/* Header */}
            <div className="px-6 py-5 border-b border-slate-100 flex items-start justify-between gap-4">
              <div>
                <div className="text-lg font-semibold text-slate-900">Change role to Picker?</div>
                <div className="mt-1 text-sm text-slate-500">
                  This will affect login credentials.
                </div>
              </div>

              <button
                type="button"
                onClick={() => setPendingRoleChange(null)}
                className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100"
                title="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="p-6 text-sm text-slate-700 space-y-3">
              <div className="flex items-start gap-3">
                <AlertTriangle className="h-5 w-5 text-amber-500 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="font-medium text-slate-900">Password will be removed</p>
                  <p className="mt-1 text-slate-600">
                    Pickers authenticate using their badge number only. The current password for this user will be replaced with the badge number.
                  </p>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3">
              <button
                onClick={() => setPendingRoleChange(null)}
                className="rounded-xl px-4 py-2 border border-slate-200 text-slate-700 hover:bg-slate-50"
              >
                Cancel
              </button>
              <button
                onClick={confirmRoleChange}
                className="rounded-xl bg-amber-600 px-4 py-2 text-white font-medium hover:bg-amber-700"
              >
                Yes, change to Picker
              </button>
            </div>
          </div>
        </div>
      )}

      {/* --- DELETE CONFIRM MODAL --- */}
      {deleteTarget && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setDeleteTarget(null);
          }}
        >
          <div className="w-full max-w-md rounded-2xl bg-white shadow-xl border border-slate-200 overflow-hidden">
            {/* Header */}
            <div className="px-6 py-5 border-b border-slate-100 flex items-start justify-between gap-4">
              <div>
                <div className="text-lg font-semibold text-slate-900">Delete user?</div>
                <div className="mt-1 text-sm text-slate-500">
                  This action can’t be undone.
                </div>
              </div>

              <button
                type="button"
                onClick={() => setDeleteTarget(null)}
                className="rounded-lg px-3 py-2 text-slate-600 hover:bg-slate-100"
                title="Close"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Body */}
            <div className="p-6 text-sm text-slate-700 space-y-2">
              <div>
                You are about to delete:
                <div className="mt-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
                  <div className="font-semibold text-slate-900">{deleteTarget.name}</div>
                  <div className="text-slate-500">{deleteTarget.email}</div>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div className="px-6 py-4 border-t border-slate-100 flex justify-end gap-3">
              <button
                onClick={() => setDeleteTarget(null)}
                className="rounded-xl px-4 py-2 border border-slate-200 text-slate-700 hover:bg-slate-50"
                disabled={isDeleting}
              >
                Cancel
              </button>
              <button
                onClick={confirmDelete}
                disabled={isDeleting}
                className="rounded-xl bg-red-600 px-4 py-2 text-white font-medium hover:bg-red-700 disabled:opacity-60"
              >
                {isDeleting ? "Deleting..." : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ViewUsers;
